### ISSUE TITLE
Fix broken link to the table lookups tutorial in the README file

### ISSUE THREAD

**Issue by trizin** [zama-ai/concrete-numpy#117]
I noticed that the link to the table lookups tutorial in the README file was broken. Here's the fix:

https://github.com/zama-ai/concrete-numpy/pull/112/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L133-R133

**Comment by aquint-zama** [comment]
Thanks for your feedback @trizin
