### ISSUE TITLE
Inputset for table lookups

### ISSUE THREAD

**Issue by cutukmirza** [zama-ai/concrete-numpy#28]
Hello,

I am trying to get the table lookups tutorial working, but I think I have a problem with the inputset, or there is something else that I am doing wrong. This is what I do:

```
squared = hnp.LookupTable([i ** 2 for i in range(4)])
cubed = hnp.LookupTable([i ** 3 for i in range(4)])

table = hnp.MultiLookupTable([
    [squared, cubed],
    [squared, cubed],
    [squared, cubed],
])

def f(x):
    return table[x]

t_lookup_inputset = [np.array([[0, 0], [0, 1], [0, 2]], dtype=np.uint8), np.array([[1, 1], [1, 2], [1, 3]], dtype=np.uint8), 
np.array([[2, 1], [2, 2], [2, 3]], dtype=np.uint8)]

compiler = hnp.NPFHECompiler(
    f, {"x": x}
)
print('compiling the circuit')
table_circuit = compiler.compile_on_inputset(t_lookup_inputset)
print('compile done')
```

I understand that the inputset should have 10 elements, but for the sake of simplicity I do just these 3. And after I run:
```
inp = np.array([[0, 1], [1, 1], [1, 2]], dtype=np.uint8)
print(circuit.encrypt_run_decrypt(inp))
```

I get the "RuntimeError: argument #0is not a tensor" during the encryption step. Could you help me a bit with understanding how the inputset works for these table lookups and advise what the best inputset for this case would be?

Thank you!

**Comment by umut-sahin** [comment]
Hello,

I tried to recreate the error you get but I couldn't. Here is what I did:

Created a new virtual env using:
```shell
$ python3.8 -m venv .venv
```

Activated it:
```shell
source .venv/bin/activate
```

Installed concrete-numpy:
```shell
pip install concrete-numpy
```

And ran this code:
```python
import concrete.numpy as hnp
import numpy as np

squared = hnp.LookupTable([i ** 2 for i in range(4)])
cubed = hnp.LookupTable([i ** 3 for i in range(4)])

table = hnp.MultiLookupTable([
    [squared, cubed],
    [squared, cubed],
    [squared, cubed],
])

def f(x):
    return table[x]

t_lookup_inputset = [
    np.array([[0, 0], [0, 1], [0, 2]], dtype=np.uint8),
    np.array([[1, 1], [1, 2], [1, 3]], dtype=np.uint8),
    np.array([[2, 1], [2, 2], [2, 3]], dtype=np.uint8),
]

compiler = hnp.NPFHECompiler(
    f, {"x": "encrypted"}
)
print('compiling the circuit')
table_circuit = compiler.compile_on_inputset(t_lookup_inputset)
print('compile done')

inp = np.array([[0, 1], [1, 1], [1, 2]], dtype=np.uint8)
print(table_circuit.encrypt_run_decrypt(inp))
```

This is the output I get:
```
compiling the circuit
compile done
[[0 1]
 [1 1]
 [1 8]]
```

Could you verify that it's working? And if it's not working could you share reproduction steps.

Thanks.

**Comment by cutukmirza** [comment]
Hi Metu,

Thank you for your swift reply! I just checked again, and it seems to be working without issues. I am using jupyter notebooks, so maybe I had some artifacts left from the other things I have tried. A small additional question, how do I fix the 

```
WARNING: You are currently using the software variant of concrete-csprng which does not have access to a hardware source of randomness. To ensure the security of your application, please arrange to provide a secret by using the `concrete_csprng::set_soft_rdseed_secret` function.
```
Since I am working in Python and this seems to be a Rust function?

Thank you!

Best,
Mirza

**Comment by aquint-zama** [comment]
This Warning could happen if you are a non-x86 architecture, say on Apple Silicon for example (that is my case). And in that case you cant use hardware acceleration and have slower performances. It is indeed in one of the Rust dependency of concrete-numpy.

More info on the issue here: https://community.zama.ai/t/support-for-hardware-source-of-randomness-in-docker-vm/44

**Comment by cutukmirza** [comment]
Alright, thank you very much for your help!
