### ISSUE TITLE
Could not find a version that satisfies the requirement concrete-compiler

### ISSUE THREAD

**Issue by s-naveen** [zama-ai/concrete-numpy#47]
## Summary
Followed the steps to install concrete-numpy but getting error. 

## Description
- versions affected: 0.8.0
- python version: tried on 3.9
- config (optional: HW, OS): Mac Monterey

## Step by step procedure someone should follow to trigger the bug:
-> `pip install concrete-numpy==0.8.0 `

**Output**:

`Collecting concrete-numpy==0.8.0
  Using cached concrete_numpy-0.8.0-py3-none-any.whl (68 kB)
Collecting matplotlib<4.0.0,>=3.5.1
  Using cached matplotlib-3.6.2-cp39-cp39-macosx_10_12_x86_64.whl (7.3 MB)
Collecting torch<2.0.0,>=1.10.2
  Using cached torch-1.13.0-cp39-none-macosx_10_9_x86_64.whl (137.9 MB)
Collecting networkx<3.0.0,>=2.6.3
  Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)
Collecting numpy<2.0.0,>=1.21.0
  Using cached numpy-1.23.5-cp39-cp39-macosx_10_9_x86_64.whl (18.1 MB)
ERROR: Could not find a version that satisfies the requirement concrete-compiler<0.20.0,>=0.19.0 (from concrete-numpy) (from versions: 0.1.1, 0.1.2, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0)
ERROR: No matching distribution found for concrete-compiler<0.20.0,>=0.19.0`

**Comment by umut-sahin** [comment]
PyPI has the version 0.19 https://pypi.org/project/concrete-compiler/0.19.0/, but it seems it's not compatible with your setup. Required glibc version got bumped recently, it could be due to that. Could you run `ldd --version ldd` on your machine and share the output?

**Comment by s-naveen** [comment]
As i stated before I am using mac there's no ldd command.

**Comment by umut-sahin** [comment]
Are you using an M1 mac? If that's the case, concrete-numpy is not natively supported yet. You can use the docker image instead, for the time being.

Otherwise, could you try running `pip install -U pip` before installing concrete-numpy?

**Comment by s-naveen** [comment]
I am using intel mac. 0.7.0 is installing and working fine. 

I tried downloading and installing wheel directly from pypi uptill 0.16 it works on latest version its throwing this error.

`ERROR: concrete_compiler-0.21.0-cp310-cp310-macosx_11_0_x86_64.whl is not a supported wheel on this platform.`

**Comment by bcm-at-zama** [comment]
Hey, I am on macOS as well, let me help you

**Comment by bcm-at-zama** [comment]
So, you're able to `pip install concrete-compiler` uphill 0.16 and it fails afterwards. Strange

Are you with python 3.9 (I have this impression in this comment https://github.com/zama-ai/concrete-numpy/issues/47#issue-1457629025) or 3.10 (I have this impression in this comment https://github.com/zama-ai/concrete-numpy/issues/47#issuecomment-1323907868)

Also, you're on macOS 11, I am on macOS 12:
```
sw_vers
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83
```
I am not sure if it makes a difference but it is to be noted

**Comment by bcm-at-zama** [comment]
Can we organise a zoom call to debug this? It may be easier

**Comment by youben11** [comment]
Could you try `pip3.9 install concrete-numpy==0.8.0` (you might need to specify the pip version here)?

**Comment by umut-sahin** [comment]
Hey,

GItHub repository being private doesn't affect PyPI in any way. Python packages are uploaded to PyPI, they are not fetched from GitHub.

And v0.19.0 of concrete-compiler is on PyPI: https://pypi.org/project/concrete-compiler/0.19.0/#files, could you try to install the `whl` file manually using `pip install /path/to/downloaded.whl` and share the error you're getting?

Thanks.

**Comment by aquint-zama** [comment]
I reproduce the same issue with old version of pip
```
root@f6bb8e0b6107:/data# pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

root@f6bb8e0b6107:/data# pip install concrete-compiler==0.19.0
ERROR: Could not find a version that satisfies the requirement concrete-compiler==0.19.0 (from versions: none)
ERROR: No matching distribution found for concrete-compiler==0.19.0
```
while it's ok when using the updated version pip3:
```
root@f6bb8e0b6107:/data# pip3 --version
pip 22.3.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)

root@f6bb8e0b6107:/data# pip3 install concrete-compiler==0.19.0
Collecting concrete-compiler==0.19.0
  Downloading concrete_compiler-0.19.0-cp38-cp38-manylinux_2_28_x86_64.whl (58.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.6/58.6 MB 29.3 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.23.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 59.3 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from concrete-compiler==0.19.0) (45.2.0)
Collecting PyYAML
  Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 701.2/701.2 kB 59.5 MB/s eta 0:00:00
Installing collected packages: PyYAML, numpy, concrete-compiler
Successfully installed PyYAML-6.0 concrete-compiler-0.19.0 numpy-1.23.5
```

I think this is related to upgrading pip issue on ubuntu (see [here](https://askubuntu.com/questions/1394163/why-is-pip-not-upgrading-cleanly-on-ubuntu-20-04-lts))

**Comment by NielsPichon** [comment]
@aquint-zama That was indeed a related issue. It seems there are 2 pip versions on my machine.

```
>> /home/niels/.local/bin/pip --version
pip 22.3.1 from /home/niels/.local/lib/python3.8/site-packages/pip (python 3.8)

>> pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```
Not sure what happened given this is a fresh WSL install... But either way it works now when using the latest pip verison🤷.

Thanks for your help :)

**Comment by umut-sahin** [comment]
Seems to be resolved. Please create another issue if the problem is persisting.
